# Generated by Django 2.1.5 on 2019-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='Имя продукта')),
                ('product_moddate', models.DateTimeField(auto_now=True, verbose_name='Дата модификации продукта')),
                ('product_adddate', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления продукта')),
                ('product_cost', models.IntegerField(verbose_name='Базовая стоимость продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код роли')),
                ('role_name', models.CharField(max_length=30, verbose_name='Название роли')),
            ],
        ),
    ]
