# Generated by Django 2.1.5 on 2019-03-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='I', on_delete=django.db.models.deletion.PROTECT, to='ofd_app.OrderStatus', verbose_name='Статус'),
        ),
    ]
