# Generated by Django 2.1.5 on 2019-03-22 02:08

from django.db import migrations

def assign_permissions_to_admin(apps, schema_editor):
    OrderStatus = apps.get_model('ofd_app', 'OrderStatus')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model("auth","Group")
    content_type = ContentType.objects.get_for_model(OrderStatus)
    permission = Permission.objects.get_or_create(codename='manage_order_status', name='Can manage order statuses', content_type=content_type)
    permissions = ['manage_order_status', 'add_user', 'change_user', 'delete_user', 'view_user', 'change_productuserrel', 'add_product', 'change_product', 'view_product', 'delete_product']
    admin = Group.objects.get(name='Admin')
    permission = Permission.objects.all().filter(codename__in=permissions)
    print(permission)
    admin.permissions.add(*permission)
    admin.save()

def assign_permissions_to_manager(apps, schema_editor):
    OrderStatus = apps.get_model('ofd_app', 'OrderStatus')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model("auth","Group")
    permissions = ['add_user', 'change_user', 'delete_user', 'view_user', 'view_product']
    permission = Permission.objects.all().filter(codename__in=permissions)
    manager = Group.objects.get(name='Manager')
    manager.permissions.add(*permission)
    manager.save()

def assign_permissions_to_user(apps, schema_editor):
    OrderStatus = apps.get_model('ofd_app', 'OrderStatus')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model("auth","Group")
    permissions = ['view_product']
    permission = Permission.objects.all().filter(codename__in=permissions)
    user = Group.objects.get(name='User')
    user.permissions.add(*permission)
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0002_order_status'),
    ]

    operations = [
        migrations.RunPython(assign_permissions_to_admin),
        migrations.RunPython(assign_permissions_to_manager),
        migrations.RunPython(assign_permissions_to_user),
    ]
