# Generated by Django 2.1.5 on 2019-03-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0004_remove_orderstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
