# Generated by Django 2.1.5 on 2019-04-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0005_auto_20190331_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='Название статуса'),
        ),
    ]
