# Generated by Django 2.1.5 on 2019-04-03 00:15

from django.db import migrations, models

def fill_status_names(apps, schema_editor):
    OrderStatus = apps.get_model('ofd_app', 'OrderStatus')
    status = OrderStatus.objects.get(code='I')
    status.name = 'В работе'
    status.save()
    status = OrderStatus.objects.get(code='A')
    status.name = 'Завершен'
    status.save()
    status = OrderStatus.objects.get(code='R')
    status.name = 'Отклонен'
    status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0006_orderstatus_name'),
    ]

    operations = [
        migrations.RunPython(fill_status_names),
    ]
