# Generated by Django 2.2 on 2019-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0007_orderstatus_fill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(default=12345678, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.CharField(max_length=100, verbose_name='Организация'),
        ),
    ]
