# Generated by Django 2.2 on 2019-04-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0008_inn_org_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(null=True, verbose_name='Ответ от администратора'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=12, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='codes',
            field=models.TextField(null=True, verbose_name='Коды активации'),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=123, verbose_name='Итоговая стоимость для одного продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ofd_app.Product', verbose_name='Заказанный продукт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сделавший заказ'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
