# Generated by Django 2.2 on 2019-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0009_new_order_model_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.NullBooleanField(verbose_name='Статус оплаты заказа'),
        ),
    ]
