# Generated by Django 2.2 on 2019-08-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofd_app', '0011_auto_20190622_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_payment',
            field=models.DateField(null=True, verbose_name='Дата оплаты заказа'),
        ),
    ]
